$report = @{
  results = @(
    @{file="rujinshiyin.md"; slug="rujinshiyin"; title="如金似银"; facts=@(@{field="曲名";value="如金似银";source="file";verified=$true},@{field="P主";value="hefengsmiley";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="rujiu.md"; slug="rujiu"; title="如旧"; facts=@(@{field="曲名";value="如旧";source="file";verified=$true},@{field="P主";value="YGY";source="file/api";verified=$true},@{field="演唱";value="洛天依, 乐正绫";source="file";verified=$true},@{field="发行日期";value="2016-01-25";source="file";verified=$true},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="BV1Ss411R7m2";source="file/api";verified=$true},@{field="播放量";value="29.3万";source="file";verified=$true;api_value="292883"});overall_verdict="confirmed";suspicious=$false}
    @{file="rulian.md"; slug="rulian"; title="入殓"; facts=@(@{field="曲名";value="入殓";source="file";verified=$true},@{field="P主";value="洛劫";source="file/api";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="2019-07-18";source="file";verified=$true},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="BV1ut41137YZ";source="file/api";verified=$true},@{field="播放量";value="1.3万";source="file";verified=$true;api_value="13037"});overall_verdict="confirmed";suspicious=$false}
    @{file="ruobilin.md"; slug="ruobilin"; title="若比邻"; facts=@(@{field="曲名";value="若比邻";source="file";verified=$true},@{field="P主";value="mengjingjimjgechenqiaoyi";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="ruochongzhongwentianci.md"; slug="ruochongzhongwentianci"; title="弱虫モンブラン【中文填词】"; facts=@(@{field="曲名";value="弱虫モンブラン【中文填词】";source="file";verified=$true},@{field="P主";value="beiaisama";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="ruo-jian-xing-fei-nan-xue.md"; slug="ruo-jian-xing-fei-nan-xue"; title="弱 碱 性 费 南 雪"; facts=@(@{field="曲名";value="弱 碱 性 费 南 雪";source="file";verified=$true},@{field="P主";value="纯白";source="file/api";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="2020-05-24";source="file";verified=$true},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="BV1kt4y1C7Ge";source="file/api";verified=$true},@{field="播放量";value="20.5万";source="file";verified=$true;api_value="205298"});overall_verdict="confirmed";suspicious=$false}
    @{file="ruomingyuebuzai.md"; slug="ruomingyuebuzai"; title="若明月不再"; facts=@(@{field="曲名";value="若明月不再";source="file";verified=$true},@{field="P主";value="jiangwuluanwan";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="ruonengyouworanjinhuahuodaoyingyiqiyihuishenming.md"; slug="ruonengyouworanjinhuahuodaoyingyiqiyihuishenming"; title="若能由我燃尽花火倒影一期一会神明"; facts=@(@{field="曲名";value="若能由我燃尽花火倒影一期一会神明";source="file";verified=$true},@{field="P主";value="weidivd";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="2024-08-30";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="ruorenshengzhiyoudieluone.md"; slug="ruorenshengzhiyoudieluone"; title="若人生只有跌落呢"; facts=@(@{field="曲名";value="若人生只有跌落呢";source="file";verified=$true},@{field="P主";value="qianmengli";source="file/api";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="2024-10-25";source="file";verified=$true},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="BV1sJyDYMEZG";source="file/api";verified=$true},@{field="播放量";value="5.6万";source="file";verified=$true;api_value="56480"});overall_verdict="confirmed";suspicious=$false}
    @{file="ruoshui.md"; slug="ruoshui"; title="若水"; facts=@(@{field="曲名";value="若水";source="file";verified=$true},@{field="P主";value="xiejiaojiaozhu";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="ruoshuisanqian.md"; slug="ruoshuisanqian"; title="弱水三千"; facts=@(@{field="曲名";value="弱水三千";source="file";verified=$true},@{field="P主";value="nalanxunfeng";source="file";verified=$true},@{field="演唱";value="洛天依, 言和";source="file";verified=$true},@{field="发行日期";value="2014-12-21";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="41.6万";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="ruoyemeng.md"; slug="ruoyemeng"; title="若耶梦"; facts=@(@{field="曲名";value="若耶梦";source="file";verified=$true},@{field="P主";value="wumingshe";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="ruqinzhe.md"; slug="ruqinzhe"; title="入侵者"; facts=@(@{field="曲名";value="入侵者";source="file";verified=$true},@{field="P主";value="gujicode";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="2017-10-29";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="3.7万";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="ruruochujian.md"; slug="ruruochujian"; title="如若初见"; facts=@(@{field="曲名";value="如若初见";source="file";verified=$true},@{field="P主";value="tamlite";source="file";verified=$true},@{field="演唱";value="洛天依, 言和";source="file";verified=$true},@{field="发行日期";value="";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="rushiwowen.md"; slug="rushiwowen"; title="如是我闻"; facts=@(@{field="曲名";value="如是我闻";source="file";verified=$true},@{field="P主";value="jindawanggold";source="file";verified=$true},@{field="演唱";value="洛天依, 言和";source="file";verified=$true},@{field="发行日期";value="2016-12-31";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="1.4万";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="rushui.md"; slug="rushui"; title="入睡"; facts=@(@{field="曲名";value="入睡";source="file";verified=$true},@{field="P主";value="mousansheng";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="2021-01-11";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="ruxi.md"; slug="ruxi"; title="如戏"; facts=@(@{field="曲名";value="如戏";source="file";verified=$true},@{field="P主";value="芹菜猪肉大馄饨";source="file/api";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="2017-02-01";source="file";verified=$true},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="BV1es41187L5";source="file/api";verified=$true},@{field="播放量";value="39.9万";source="file";verified=$true;api_value="399175"});overall_verdict="confirmed";suspicious=$false}
    @{file="ruyisuanpancover-huanxiaoyi.md"; slug="ruyisuanpancover-huanxiaoyi"; title="如意算盘（Cover 幻晓伊）"; facts=@(@{field="曲名";value="如意算盘（Cover 幻晓伊）";source="file";verified=$true},@{field="P主";value="yishuiuryan";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$false;note="API title shows 千本 cover"},@{field="发行日期";value="2020-04-01";source="file";verified=$false;note="API pubdate timezone gives 2020-04-02 CST"},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="BV1SZ4y1j74n";source="file/api";verified=$true},@{field="播放量";value="2010";source="file";verified=$false;api_value="201";note="File says 2010, API says 201"});overall_verdict="partial";suspicious=$false}
    @{file="ruyuan.md"; slug="ruyuan"; title="如愿"; facts=@(@{field="曲名";value="如愿";source="file";verified=$true},@{field="P主";value="tmzhusangsang";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="ruyunli.md"; slug="ruyunli"; title="入云里"; facts=@(@{field="曲名";value="入云里";source="file";verified=$true},@{field="P主";value="tayunshe";source="file";verified=$true},@{field="演唱";value="洛天依, 乐正绫, 乐正龙牙, 言和, 心华, 徵羽摩柯";source="file";verified=$true},@{field="发行日期";value="2023-06-24";source="file";verified=$true},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="BV1kW4y1D7cc";source="file/api";verified=$true},@{field="播放量";value="556810";source="file";verified=$false;api_value="5568";note="API returns 5568, file has 556810"});overall_verdict="conflict";suspicious=$true}
    @{file="ruyunlidisanbang.md"; slug="ruyunlidisanbang"; title="入云里·第三棒"; facts=@(@{field="曲名";value="入云里·第三棒";source="file";verified=$true},@{field="P主";value="tayunshe";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="2023-06-24";source="file";verified=$true},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="BV1kW4y1D7cc";source="file/api";verified=$true},@{field="播放量";value="556810（合辑）";source="file";verified=$false;api_value="5568";note="Same video as ruyunli"});overall_verdict="conflict";suspicious=$true}
    @{file="ruyunlidiwubang.md"; slug="ruyunlidiwubang"; title="入云里·第五棒"; facts=@(@{field="曲名";value="入云里·第五棒";source="file";verified=$true},@{field="P主";value="tayunshe";source="file";verified=$true},@{field="演唱";value="洛天依, 乐正绫";source="file";verified=$true},@{field="发行日期";value="2023-06-24";source="file";verified=$true},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="BV1kW4y1D7cc";source="file/api";verified=$true},@{field="播放量";value="556810（合辑）";source="file";verified=$false;api_value="5568";note="Same video as ruyunli"});overall_verdict="conflict";suspicious=$true}
    @{file="sachikodeja-vutouwenzidchaqufanzi-dave-rodgers.md"; slug="sachikodeja-vutouwenzidchaqufanzi-dave-rodgers"; title="【Sachiko】Deja Vu"; facts=@(@{field="曲名";value="【Sachiko】Deja Vu（《头文字D》插曲）（翻自 Dave Rodgers）";source="file";verified=$true},@{field="P主";value="tayunshe";source="file";verified=$true},@{field="演唱";value="Sachiko";source="file";verified=$true},@{field="发行日期";value="2019-04-08";source="file";verified=$true},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="BV1Db411u7cy";source="file/api";verified=$true},@{field="播放量";value="9187";source="file";verified=$true;api_value="9187"});overall_verdict="confirmed";suspicious=$false}
    @{file="sachiko-shenwei-gumidancing-to-night-junzuiduanhanglufanzi-shant.md"; slug="sachiko-shenwei-gumidancing-to-night-junzuiduanhanglufanzi-shant"; title="【Sachiko 神威がくぽ Gumi】Dancing to Night"; facts=@(@{field="曲名";value="【Sachiko 神威がくぽ Gumi】Dancing to Night ~君への最短ワープ航路~（翻自 杉田智和、徳留慎乃佑、木村昴）";source="file";verified=$true},@{field="P主";value="tayunshe";source="file";verified=$true},@{field="演唱";value="Sachiko, 神威がくぽ, Gumi";source="file";verified=$true},@{field="发行日期";value="2019-04-30";source="file";verified=$false;note="API gives 2019-05-01 CST"},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="BV1L4411t7k4";source="file/api";verified=$true},@{field="播放量";value="5686";source="file";verified=$true;api_value="5686"});overall_verdict="partial";suspicious=$false}
    @{file="sahaladegushi.md"; slug="sahaladegushi"; title="撒哈拉的故事"; facts=@(@{field="曲名";value="撒哈拉的故事";source="file";verified=$true},@{field="P主";value="bingpan";source="file/api";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="2024-01-01";source="file";verified=$true},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="BV1S94y1u7qq";source="file/api";verified=$true},@{field="播放量";value="18871";source="file";verified=$false;api_value="1887";note="File has 18871, API returns 1887"});overall_verdict="conflict";suspicious=$true}
    @{file="saibomengjiangnv.md"; slug="saibomengjiangnv"; title="赛博孟姜女"; facts=@(@{field="曲名";value="赛博孟姜女";source="file";verified=$true},@{field="P主";value="jiangwuluanwan";source="file/api";verified=$true},@{field="演唱";value="洛天依, 乐正绫";source="file";verified=$true},@{field="发行日期";value="2020-07-16";source="file";verified=$true},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="BV1bC4y1877G";source="file/api";verified=$true},@{field="播放量";value="8.2万";source="file";verified=$true;api_value="82508"});overall_verdict="confirmed";suspicious=$false}
    @{file="saichewuqu.md"; slug="saichewuqu"; title="赛车舞曲"; facts=@(@{field="曲名";value="赛车舞曲";source="file";verified=$true},@{field="P主";value="meijintaichen";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="2024-07-14";source="file";verified=$true},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="BV1nS411w7BE";source="file/api";verified=$true},@{field="播放量";value="32717";source="file";verified=$false;api_value="3271";note="File has 32717, API returns 3271"});overall_verdict="conflict";suspicious=$true}
    @{file="sailungaidi.md"; slug="sailungaidi"; title="塞伦盖蒂"; facts=@(@{field="曲名";value="塞伦盖蒂";source="file";verified=$true},@{field="P主";value="yizhihuobengluantiaodekafeivckafei";source="file";verified=$true},@{field="演唱";value="";source="file";verified=$false},@{field="发行日期";value="2023-12-17";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="约5.4万";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="sain.md"; slug="sain"; title="SaIN"; facts=@(@{field="曲名";value="SaIN";source="file";verified=$true},@{field="P主";value="zhoucun";source="file";verified=$true},@{field="演唱";value="洛天依, 言和";source="file";verified=$true},@{field="发行日期";value="2016-11-17";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="约93.5万";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="sairenbodian.md"; slug="sairenbodian"; title="塞壬波点"; facts=@(@{field="曲名";value="塞壬波点";source="file";verified=$true},@{field="P主";value="zhihuixiebaledehuapianp";source="file";verified=$true},@{field="演唱";value="洛天依, 乐正绫, 心华, 星尘";source="file";verified=$true},@{field="发行日期";value="2017-03-19";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="约12.5万";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="saixiaqu.md"; slug="saixiaqu"; title="塞下曲"; facts=@(@{field="曲名";value="塞下曲·再一年为君征战";source="file";verified=$true},@{field="P主";value="heibaijun";source="file";verified=$true},@{field="演唱";value="洛天依, 乐正绫";source="file";verified=$true},@{field="发行日期";value="2016-09-21";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="约27.1万";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="samidare.md"; slug="samidare"; title="Samidare"; facts=@(@{field="曲名";value="Samidare";source="file";verified=$true},@{field="P主";value="zhihuixiebaledehuapianp";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="sanbeikongcheng.md"; slug="sanbeikongcheng"; title="三杯空城"; facts=@(@{field="曲名";value="三杯空城";source="file";verified=$true},@{field="P主";value="cop";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="2014-02-28";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="约25.4万";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="sanguolian.md"; slug="sanguolian"; title="三国恋"; facts=@(@{field="曲名";value="三国恋";source="file";verified=$true},@{field="P主";value="kamiyadawangzhanghaozhuxiao";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="sanhuaouranxiangyudeshijie.md"; slug="sanhuaouranxiangyudeshijie"; title="伞话—偶然相遇的世界"; facts=@(@{field="曲名";value="伞话—偶然相遇的世界";source="file";verified=$true},@{field="P主";value="wugui";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="2014-01-23";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="约2.9万";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="sanjinfen.md"; slug="sanjinfen"; title="三晋分"; facts=@(@{field="曲名";value="三晋分";source="file";verified=$true},@{field="P主";value="kelejun";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="sanqianshijieyashajin.md"; slug="sanqianshijieyashajin"; title="三千世界鸦杀尽"; facts=@(@{field="曲名";value="三千世界鸦杀尽";source="file";verified=$true},@{field="P主";value="huazhiji";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="2012-11-23";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="约73.0万";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="sanshengleizhanshang.md"; slug="sanshengleizhanshang"; title="三声泪沾裳"; facts=@(@{field="曲名";value="三声泪沾裳";source="file";verified=$true},@{field="P主";value="aolianduohuanxiangqupbuyueshuicangqpanqingp";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="sanshijian.md"; slug="sanshijian"; title="三世笺"; facts=@(@{field="曲名";value="三世笺";source="file";verified=$true},@{field="P主";value="yinqueshiting";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="santoulongzhilian.md"; slug="santoulongzhilian"; title="三头龙之恋"; facts=@(@{field="曲名";value="三头龙之恋";source="file";verified=$true},@{field="P主";value="yujianliu";source="file";verified=$true},@{field="演唱";value="洛天依, 乐正绫, 言和";source="file";verified=$true},@{field="发行日期";value="2023-05-30";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="约2.4万";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="sanwannianzhiqiandianyingxiongchumoyuanshishidaizhutiquxingchenl.md"; slug="sanwannianzhiqiandianyingxiongchumoyuanshishidaizhutiquxingchenl"; title="三万年之前"; facts=@(@{field="曲名";value="三万年之前（电影《熊出没·原始时代》主题曲）（星尘、洛天依）";source="file";verified=$true},@{field="P主";value="regretful-love";source="file";verified=$true},@{field="演唱";value="星尘, 洛天依";source="file";verified=$true},@{field="发行日期";value="";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="sanxiaming.md"; slug="sanxiaming"; title="伞下铭"; facts=@(@{field="曲名";value="伞下铭";source="file";verified=$true},@{field="P主";value="zhuxiaoshengzoki";source="file";verified=$true},@{field="演唱";value="洛天依, 言和";source="file";verified=$true},@{field="发行日期";value="2018-07-08";source="file";verified=$true},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="BV1hs411p7XR";source="api";verified=$true},@{field="播放量";value="";source="file";verified=$false;api_value="74165"});overall_verdict="partial";suspicious=$false}
    @{file="sanxingqingshichuyinluotianyi.md"; slug="sanxingqingshichuyinluotianyi"; title="三行情诗（初音ミク、洛天依）"; facts=@(@{field="曲名";value="三行情诗（初音ミク、洛天依）";source="file";verified=$true},@{field="P主";value="regretful-love";source="file";verified=$true},@{field="演唱";value="洛天依, 初音未来";source="file";verified=$true},@{field="发行日期";value="";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="sanyuanse-2.md"; slug="sanyuanse-2"; title="三原色"; facts=@(@{field="曲名";value="三原色";source="file";verified=$true},@{field="P主";value="aolianduohuanxiangqupbuyueshuicangqpanqingp";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="sanyuanse-yongye.md"; slug="sanyuanse-yongye"; title="三原色-永夜"; facts=@(@{field="曲名";value="三原色-永夜";source="file";verified=$true},@{field="P主";value="aolianduohuanxiangqupbuyueshuicangqpanqingp";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="san-yue-yu.md"; slug="san-yue-yu"; title="三 月 雨"; facts=@(@{field="曲名";value="三 月 雨";source="file";verified=$true},@{field="P主";value="regretful-love";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="sanyueyuchunmianzhe.md"; slug="sanyueyuchunmianzhe"; title="三月与春眠者"; facts=@(@{field="曲名";value="三月与春眠者";source="file";verified=$true},@{field="P主";value="xiuzhengcaowww";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$true},@{field="发行日期";value="";source="file";verified=$false},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="";source="file";verified=$false},@{field="播放量";value="";source="file";verified=$false});overall_verdict="unverifiable";suspicious=$false}
    @{file="saolei.md"; slug="saolei"; title="扫雷"; facts=@(@{field="曲名";value="扫雷";source="file";verified=$true},@{field="P主";value="padi";source="file";verified=$true},@{field="演唱";value="洛天依, 乐正绫";source="file";verified=$true},@{field="发行日期";value="2017-02-27";source="file";verified=$true},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="BV1Fx41117Ur";source="api";verified=$true},@{field="播放量";value="";source="file";verified=$false;api_value="16310"});overall_verdict="partial";suspicious=$false}
    @{file="sapphire-tearscanglei.md"; slug="sapphire-tearscanglei"; title="Sapphire Tears~苍泪~"; facts=@(@{field="曲名";value="Sapphire Tears~苍泪~";source="file";verified=$true},@{field="P主";value="rotbohnexiaodou";source="file";verified=$true},@{field="演唱";value="洛天依, 乐正绫";source="file";verified=$true},@{field="发行日期";value="2018-05-21";source="file";verified=$true},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="BV1gp411o7ac";source="api";verified=$true},@{field="播放量";value="";source="file";verified=$false;api_value="11528"});overall_verdict="partial";suspicious=$false}
    @{file="say-a-good-bye.md"; slug="say-a-good-bye"; title="Say a Good Bye"; facts=@(@{field="曲名";value="Say a Good Bye";source="file";verified=$true},@{field="P主";value="kevinz";source="file";verified=$true},@{field="演唱";value="洛天依";source="file";verified=$false;note="API shows 洛天依Ft.星尘"},@{field="发行日期";value="2017-08-26";source="file";verified=$true},@{field="首发平台";value="bilibili";source="file";verified=$true},@{field="引擎";value="vocaloid";source="file";verified=$true},@{field="视频ID";value="BV1Ax41187mU";source="api";verified=$true},@{field="播放量";value="";source="file";verified=$false;api_value="25291"});overall_verdict="partial";suspicious=$false}
  )
  report_metadata = @{
    batch = "Batch_055"
    total_files = 50
    summary = @{}
  }
}

# Calculate summary
$confirmed = ($report.results | Where-Object { $_.overall_verdict -eq "confirmed" }).Count
$partial = ($report.results | Where-Object { $_.overall_verdict -eq "partial" }).Count
$conflict = ($report.results | Where-Object { $_.overall_verdict -eq "conflict" }).Count
$unverifiable = ($report.results | Where-Object { $_.overall_verdict -eq "unverifiable" }).Count
$suspicious = ($report.results | Where-Object { $_.suspicious }).Count

$report.report_metadata.summary = @{
  confirmed = $confirmed
  partial = $partial
  conflict = $conflict
  unverifiable = $unverifiable
  suspicious = $suspicious
  file_not_found = 0
}

$jsonPath = "D:\数据收集\luotianyi-db\processed\rag\.pipeline\verification_reports\Batch_055_verification.json"
$report | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath $jsonPath -Encoding UTF8

Write-Host "=== Batch_055 Verification Report ==="
Write-Host "Saved to: $jsonPath"
Write-Host "Summary:"
Write-Host "  Total: 50"
Write-Host "  Confirmed: $confirmed"
Write-Host "  Partial: $partial"
Write-Host "  Conflict: $conflict"
Write-Host "  Unverifiable: $unverifiable"
Write-Host "  Suspicious (flagged for review): $suspicious"
Write-Host "  File Not Found: 0"
